superna9999/meta-meson

recipes-bsp/u-boot/amlogic-fip-libretech-cc_v2017.11.bb

Using prebuilt fip binaries eliminates the needs for an extra toolchain and syncs the OE build with LibreElec.
Buildtested only.
Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>

amlogic-fip-libretech-cc: update to v207.11 and use prebuild

---

recipes-bsp/aml-autoscript/files/aml_autoscript.cmd

With these minor fixes, I was able to test that the load/run of aml_autoscript from MMC worked fine on the nexbox-a95x-s905x when starting from the vendor u-boot in eMMC.
With Amlogic vendor u-boot, from u-boot prompt, use `run recovery_from_sdcard` which loads/runs the aml_autoscript from MMC.

Fix aml-autoscript 

---

conf/machine/amlogic-p212.conf
conf/machine/khadas-vim.conf

While testing amlogic-image-headless-sd on khadas-vim and
amlogic-p212, both kernels seem to detect the SD card slot as mmcblk0.
Signed-off-by: Kevin Hilman <khilman@baylibre.com>

use mmcblk0 on kvim and p212

---

recipes-bsp/alsa-board-conf/files/amlogic-s400/board.conf

The amlogic-s400 audio path does not support every audio rate & format.
Use alsa plugins to specify the rate and format of the audio streams.
Signed-off-by: Loys Ollivier <lollivier@baylibre.com>

amlogic-s400 configure the default alsa streams rate and format

---

recipes-multimedia/pulseaudio/pulseaudio/0001-s400-set-default-sink-source-to-alsa-default.patch
recipes-multimedia/pulseaudio/pulseaudio_%.bbappend

The amlogic-s400 has default alsa streams defined with correct rate and
format.
Configure pulseaudio to use them by default.
Signed-off-by: Loys Ollivier <lollivier@baylibre.com>

pulseaudio: configure the default streams to alsa for the amlogic-s400

---

recipes-kernel/linux/linux-yocto-meson32-5.2/0001-UPSTREAM-drm-rcar-du-Fix-build-error.patch
recipes-kernel/linux/linux-yocto-meson32_5.2.bb

Add linux upstream patch to fix kernel build error dependency.
When compiling linux kernel using arch/arm/configs/multi_v7_defconfig it
generates the next error because of missing dependency:
| arm-poky-linux-gnueabi-ld.bfd: drivers/gpu/drm/rcar-du/rcar_lvds.o:(.rodata+0x4): undefined reference to `drm_atomic_helper_connector_reset'
| arm-poky-linux-gnueabi-ld.bfd: drivers/gpu/drm/rcar-du/rcar_lvds.o:(.rodata+0x10): undefined reference to `drm_helper_probe_single_connector_modes'
| arm-poky-linux-gnueabi-ld.bfd: drivers/gpu/drm/rcar-du/rcar_lvds.o:(.rodata+0x24): undefined reference to `drm_atomic_helper_connector_duplicate_state'
| arm-poky-linux-gnueabi-ld.bfd: drivers/gpu/drm/rcar-du/rcar_lvds.o:(.rodata+0x28): undefined reference to `drm_atomic_helper_connector_destroy_state'
| …

linux-yocto-meson32 5.2: Fix kernel build error

---

recipes-kernel/kernel-modules/kernel-module-mali-utgard_r7p0-00rel1-meson-gx.bb

Move to mali-utgard_r7p0-00rel1-meson-gx and use latest fixed version for v5.0
Signed-off-by: Daniel Gomez <dagmcr@gmail.com>

kernel-module-mali-utgard: Update to fix build error

---

recipes-kernel/linux/linux-meson64-5.2/0233-UPSTREAM-perf-Make-perf-able-to-build-with-latest-libbfd.patch
recipes-kernel/linux/linux-meson64-5.4/0068-UPSTREAM-perf-Make-perf-able-to-build-with-latest-libbfd.patch
recipes-kernel/linux/linux-meson64_5.2.bb
recipes-kernel/linux/linux-meson64_5.4.bb

Linux kernel patch makes perf able to build with latest libbfd
Fixes:
| /workdir/build/tmp/work/libretech_ac-poky-linux/perf/1.0-r9/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/ld: /workdir/build/tmp/work/libretech_ac-poky-linux/perf/1.0-r9/perf-1.0/perf-in.o: in function `find_address_in_section':
| /usr/src/debug/perf/1.0-r9/perf-1.0/tools/perf/util/srcline.c:200: undefined reference to `bfd_get_section_flags'
| /workdir/build/tmp/work/libretech_ac-poky-linux/perf/1.0-r9/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/ld: /usr/src/debug/perf/1.0-r9/perf-1.0/tools/perf/util/srcline.c:204: undefined reference to `bfd_get_section_vma'
| …

linux-meson64: fix perf build libbfd error

---

recipes-bsp/s905-autoscript-multiboot/files/aml_autoscript.cmd

U-Boot reboot command is 'reset' and not 'reboot'. Therfore, script
fails trying to reboot the board with the wrong command.
Signed-off-by: Daniel Gomez <dagmcr@gmail.com>

s905-autoscript-multiboot: Fix u-boot reset command

---

recipes-kernel/kernel-modules/kernel-module-mali-utgard_r7p0-00rel1-meson-gx.bb

Include patch to fix:
| /workdir/build/tmp/work/libretech_ac-poky-linux/kernel-module-mali-utgard/r7p0-00rel1-meson-gx-r0/git/driver/src/devicedrv/mali/linux/mali_osk_time.c:57:9: error: implicit declaration of function 'ktime_get_boot_ns'; did you mean 'ktime_get_raw_ns'? [-Werror=implicit-function-declaration]
|    57 |  return ktime_get_boot_ns();
|       |         ^~~~~~~~~~~~~~~~~
|       |         ktime_get_raw_ns
Signed-off-by: Daniel Gomez <dagmcr@gmail.com>

kernel-module-mali-utgard: Include fix for kernels 5.3 or greater

---

classes/image_types_meson.bbclass
conf/machine/include/khadas-vim3-dtb.inc
conf/machine/khadas-vim3.conf
recipes-bsp/u-boot/u-boot-meson-gx/fit.cfg
recipes-bsp/u-boot/u-boot-meson-gx_2020.10.bb
recipes-kernel/linux/linux-yocto%.bbappend

Handful of cleanups, fixes to use linux-yocto-dev kernel with FIT support.  
Initial focus on khadas-vim3, but done in a way to be generic for all of `meson-gx` machines that support mainline u-boot.

khadas-vim3: use linux-yocto-dev, FIT image, fix WIC etc.

---

classes/kernel-uimage-meson.bbclass

Hey guys,
Sorry I've not been here for a while, but coming back to do some maintenance on the linux-yocto recipes for the VIM3.
Fixup linux-yocto_% to have a COMPATIBLE_MACHINE for <target>-sdboot targets.
Also fix do_uboot_mkimage where UBOOT_ENTRYPOINT is not defined.
I had an issue where uboot mkimage would fail due to a missing UBOOT_ENTRYSYMBOL was not defined.  I fixed this by replicating what us done in the base kernel-umage class.  Not 100% if this is correct, but it works for me on my VIM3.
Cheers
/Matt

Fixup linux-yocto to build for -sdboot targets

---

conf/machine/khadas-vim3.conf

Use the binary FDT instead of the device tree source when booting.
The board boots now without having to modifying boot params after flashing.
A question, how to I modify the device-tree with fdt set now before booting?  I have a quick scan of the web and can't find anything obvious.

Use .dtb instead of .dts in boot config

---

recipes-kernel/linux/linux-yocto%.bbappend

Including linux-yocto-virtualization.inc in the linix-yocto recipes is not needed as it is pulled in for both linux-yocto-5.x and
linux-yocto-dev from the meta-virtualization recipes.
Before removing this, there were a number of "WARNING: Duplicate inclusion for ..." warnings in the build.
@khilman I know you committed this in an earlier patch set, can you review that you are happy with this?
I have tested using both linux-yocto-5.4 and linux-yocto-5.8 (from the master Poky branch) and docker works fine for me.  I have not tested on linux-yocto-dev, but from code inspection I believe it should work fine.

Remove dupliacte include of linux-yocto-virtualization.inc

---

README.md
conf/machine/khadas-vim3l-sdboot.conf
conf/machine/khadas-vim3l.conf

Convert khadas-vim3l machine to use mainline u-boot.  Vendor u-boot
machine renamed to khadas-vim3l-sdboot to match other machines.
Signed-off-by: Kevin Hilman <khilman@baylibre.com>

khadas-vim3l: add mainline-uboot

---

recipes-bsp/u-boot/u-boot-meson-gx/0001-ARM-dts-sync-amlogic-G12A-SM1-DT-from-Linux-5.9-rc1.patch
recipes-bsp/u-boot/u-boot-meson-gx/0002-board-amlogic-add-a-vim3-specific-board-support.patch
recipes-bsp/u-boot/u-boot-meson-gx/0003-configs-vim3-use-the-vim3-board-support.patch
recipes-bsp/u-boot/u-boot-meson-gx/0004-board-amlogic-vim3-add-support-for-dynamic-PCIe-enab.patch
recipes-bsp/u-boot/u-boot-meson-gx_2020.10.bb

These patches were merged upstream after v2020.10 but are useful for
VIM3* platforms to support PCIe.
Signed-off-by: Kevin Hilman <khilman@baylibre.com>

u-boot: add dynamic PCIe support

---

conf/machine/amlogic-p212.conf
conf/machine/amlogic-s400.conf
conf/machine/friendlyelec-nanopik2.conf
conf/machine/hardkernel-odroidc2.conf
conf/machine/khadas-vim.conf
conf/machine/khadas-vim3.conf
conf/machine/khadas-vim3l.conf
conf/machine/libretech-ac.conf
conf/machine/libretech-cc.conf

Use a soft assignment of UBOOT_EXTLINUX_ROOT so that you
can override it in your local.conf.
Fixes issue #107 
Signed-off-by: Matt Spencer <matthew@thespencers.me.uk>

Allow UBOOT_EXTLINUX_ROOT override in local.conf

---

README.md
kas/kas-poky-meson.yml

kas is a set-up tool for bitbake projekts. It simplifies the local.conf
and bblayer file handling. It also provides the possibility to include
configurations from other layers.
Signed-off-by: Christian Ege <ch@ege.io>

Add a basic kas config

---

README.md
conf/machine/amlogic-s905.conf
conf/machine/amlogic-s9xxx.conf
conf/machine/include/radxa-zero-dtb.inc
conf/machine/radxa-zero.conf
recipes-bsp/trusted-firmware-a/amlogic-boot-fip.bb
recipes-kernel/linux/linux-yocto/0002-FROMLIST-arm64-dts-amlogic-add-support-for-radxa-zero.patch
recipes-kernel/linux/linux-yocto_5.1%.bbappend

Addresses #146 on master branch
Also brings radxa-zero device tree patch in from lkml for kernels versions < 5.16
https://lkml.org/lkml/2021/9/9/250

Support radxa-zero using mainline u-boot. (master)

---

README.md
conf/machine/amlogic-s905.conf
conf/machine/amlogic-s9xxx.conf
conf/machine/include/radxa-zero-dtb.inc
conf/machine/radxa-zero.conf
recipes-bsp/trusted-firmware-a/amlogic-boot-fip.bb
recipes-kernel/linux/linux-yocto/0002-FROMLIST-arm64-dts-amlogic-add-support-for-radxa-zero.patch
recipes-kernel/linux/linux-yocto_5.15.bbappend

~~Haven't tested this just yet, but will shortly, submitting PR in the meantime to track here.~~
Addresses https://github.com/superna9999/meta-meson/issues/146 on kirkstone branch
Also brings the radxa-zero device tree patch in from lkml for kernels version 5.15.x
https://lkml.org/lkml/2021/9/9/250

Support radxa-zero using mainline u-boot (kirkstone)

---

conf/machine/include/amlogic-meson.inc

In addition to the wic image, also generate the wic.bmap file which allows bmaptool to efficiently copy the image.

amlogic-meson: Generate wic bmap file

---

classes/image_types_meson.bbclass

$IMAGE_NAME_SUFFIX no longer needs to be separately added to the image name, so remove it otherwise the images are not created correctly and will not boot.

classes/image_types_meson: Fix image creation

---

kas/kas-poky-meson.yml

Update variables to be compliance with last kas version. Update branch name to use same as meta-meson branch.

kas: update to support nanbield branch and last kas version
